### ISSUE TITLE
When will you be changing old twitter icon to X?

### ISSUE THREAD

**Issue by LouisOpperman** [Pictogrammers/pictogrammers.com#100]
### Describe your suggested feature

Good day.

When will you be changing the old Twitter icon to X?

Regards
Louis

**Comment by mririgoyen** [comment]
This is not the place for icon requests. You will need to make requests on whichever library's repo you would like changes/new additions. That being said, none of our libraries are maintaining any brand icons anymore, so X will never be added. You can use the unicode value for it or use a library with a specific focus on brand icons, such as SimpleIcons.
