### ISSUE TITLE
Support Material Symbols

### ISSUE THREAD

**Issue by yutamago** [Pictogrammers/pictogrammers.com#103]
### Describe your suggested feature

Google released a successor to Material Icons called Material Symbols.
See: https://fonts.google.com/icons?icon.set=Material+Symbols

On the left side you can switch back to Material Icons:
![image](https://github.com/Pictogrammers/pictogrammers.com/assets/12561505/a525ecde-f82d-43e4-ab4f-4164f3a0488b)

The new Material Symbols contain icons that are not included in the current [Material Design Icons](https://pictogrammers.com/library/mdi/)
For example `routine`:
![image](https://github.com/Pictogrammers/pictogrammers.com/assets/12561505/e126259a-c9a2-4ec0-9785-bad113562de9)

**Comment by Templarian** [comment]
@yutamago We generally add icons on a need basis rather than sync all of the `Material Symbols` icons. You can create individual requests over at the main repo: https://github.com/Templarian/MaterialDesign/issues (which we're working to move to Pictogrammers org eventually).
