### ISSUE TITLE
Generator combining existing icons

### ISSUE THREAD

**Issue by josias-levi-alvares** [Pictogrammers/pictogrammers.com#104]
### Describe your suggested feature

Hello :)

Firstable, a big thanks for Pictogrammers work <3 I've been using a lots these icons and its a real game changer !

Google recently proposed an [emoticon cooker](https://emojikitchen.dev/) able to build an icon based on 2 icons that the user selects (it does a mix of the two)
From pictogrammers, I often use icons that are already a mix of 2 symbols (like the 'add folder' with a 'folder' icon and a little 'plus' icon on the bottom right).

I wonder if the website could propose something alike to generate our own icons from existing ones ?

**Comment by mririgoyen** [comment]
Thanks, this is a duplicate of #44.
