### ISSUE TITLE
Hot water tank

### ISSUE THREAD

**Issue by jerboyspy** [Pictogrammers/pictogrammers.com#112]
### Describe your suggested feature

![IMG_6455](https://github.com/Pictogrammers/pictogrammers.com/assets/65292280/527ea8e7-5a8d-41a1-8925-10d991632fec)

**Comment by Templarian** [comment]
Please open icon issues in the respective repo: https://github.com/Pictogrammers/Memory

I have a feeling you meant MDI for home assistant icons: https://github.com/Templarian/MaterialDesign/issues
