### ISSUE TITLE
shutter-blades-open

### ISSUE THREAD

**Issue by Melm56** [Pictogrammers/pictogrammers.com#114]
### Describe your suggested feature

to have the mdi icon with the shutter closed and the blades horizontal

Pixel Editor
M20,20H18V18H4V20H2V2H20ZM18,5V4H4V5ZM18,8V6H4V8ZM18,11V9H4V11ZM18,14V12H4V14ZM18,17V15H4V17Z

**Comment by Templarian** [comment]
Please open icon issues: https://github.com/Templarian/MaterialDesign/issues
