### ISSUE TITLE
add social media icons

### ISSUE THREAD

**Issue by pgaby28** [Pictogrammers/pictogrammers.com#116]
### Describe your suggested feature

Greetings, I am a frontend developer and I use a lot the material icons for my interfaces, it would be great to add the new **twitter** icon that is now represented by an **X** and **TikTok**, as they are quite popular social networks today in idea and many customers request to have these icons on their websites. thanks!

https://twitter.com/

https://www.tiktok.com/

**Comment by Templarian** [comment]
@pgaby28 Not planned at this time. Turns out getting permission to use these is near impossible so we'll be removing all brand icons in the 8.x release.

https://github.com/Pictogrammers/brand-icons
