### ISSUE TITLE
Why still no X logo to replace Twitter icon

### ISSUE THREAD

**Issue by JPMulder** [Pictogrammers/pictogrammers.com#126]
### Describe your suggested feature

Hi
I'm searching the latest 7.4.47 library and still no X icon, Am I missing it 
https://pictogrammers.com/library/mdi/category/brand-logo/

**Comment by Templarian** [comment]
We're not adding any branding icons to the icon pack and removing all the existing ones. Legality thing.

https://github.com/Templarian/MaterialDesign/issues Use this repo.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign/issues/6602 Full explanation here.
