### ISSUE TITLE
Where are the png files?

### ISSUE THREAD

**Issue by quargh** [Pictogrammers/pictogrammers.com#17]
There is no way to download as png anymore?

**Comment by Templarian** [comment]
@quargh This is being worked on, until it's rolled out please use the 'MaterialDesignIcons Picker' extension available for all the major browsers.

**Comment by quargh** [comment]
Thank you

**Comment by mririgoyen** [comment]
Thanks for the comment. We'll be adding additional download formats in the coming releases. Thanks for your patience!
