### ISSUE TITLE
Drawable images android??

### ISSUE THREAD

**Issue by egscodes** [Pictogrammers/pictogrammers.com#18]
When the website was "https://materialdesignicons.com/" I was able to download the icons in drawable folders, but it seems the new site doesn't have that? 

I'm using Xamarin/visual studio so if there is an alternative NuGet for visual studio i guess i wouldn't mind (even though the number of pictures will be a waste of space). 

The site did use to include black/white/gray by default. (I never understood why downloading custom colors weren't easy...) 

Looking at old code i made it seems i mostly use 36.png and 24.xml (Mostly saying this since new site doesn't seem to have a size picker)

**Comment by mririgoyen** [comment]
Thanks for the comment. I sincerely apologize that functionality you relied on wasn't included in the new site. I will be investigating added this back as soon as possible.

**Comment by mririgoyen** [comment]
This has been added in #19. The site will reflect the changes approximately 10 minutes from this post. Thank you for reporting it!
