### ISSUE TITLE
Replace broken link

### ISSUE THREAD

**Issue by jhil** [Pictogrammers/pictogrammers.com#2]
From homepage, https://pictogrammers.netlify.app/icons/mdi should be https://pictogrammers.netlify.app/library/mdi!

**Comment by mririgoyen** [comment]
Resolved in https://github.com/Pictogrammers/pictogrammers-v2/pull/1.

**Comment by jhil** [comment]
Ha! Missed that.

**Comment by jhil** [comment]
Thanks @chteuchteu !
