### ISSUE TITLE
Custom size icon export

### ISSUE THREAD

**Issue by przemowcf** [Pictogrammers/pictogrammers.com#20]
Hi,

I am missing ability to export icon in custom size (like png 16x16px , or 128x128px, etc...).

Can you "restore" this feature: export icon in user-specified size and let user chosen format (**PNG** is mandatory 😄 , SVG, bmp?, gif?, svg?, etc...)? 
I've been using this feature a lot. *(Since I'm not good with "graphic programs" and they often make icon "ugly" when I shrink it 😞).*

*[quargh](https://github.com/quargh)* mentioned this under already closed issue: https://github.com/Pictogrammers/pictogrammers.com/pull/19#issuecomment-1399907028 

*Ps. Other formats than PNG and SVG, personally I do not need, and I don't remember what other formats was available on materialdesigicons page 😅*

**Comment by mririgoyen** [comment]
Thanks for reaching out. Yes, we intend to build out advanced export again. I've created #23 to capture this work. Please follow that issue for updates.

I'm going to close this issue in favor of that one. If you have any other comments or suggestions based on the acceptance criteria outlined there, please feel free to post a comment.
