### ISSUE TITLE
Set icon color to export

### ISSUE THREAD

**Issue by przemowcf** [Pictogrammers/pictogrammers.com#21]
Hi,

Now it is impossible in this new page to export icon in different colors (background & foreground) - it was possible to do this along with custom icon sizes #20 .

Please 🙏 , can you restore this functionality? This feature and #20 was most used by me.

**Comment by mririgoyen** [comment]
Thanks for reaching out. Yes, we intend to build out advanced export again. I've created #23 to capture this work. Please follow that issue for updates.

I'm going to close this issue in favor of that one. If you have any other comments or suggestions based on the acceptance criteria outlined there, please feel free to post a comment.
