### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by mririgoyen** [Pictogrammers/pictogrammers.com#3]
The current implementation of searching for icons is lackluster. I should know, I coded it. 😅 There are some limitations when performing searches on IndexedDB that are really apparent when searching for word partials.

I will be implementing full fuzzy searching for each icon library, as well as full site search, including all icon libraries and documentation.

This work is being completed in https://github.com/Pictogrammers/pictogrammers.com/pull/4.

**Comment by leeoniya** [comment]
i have some comparisons here: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

**Comment by mririgoyen** [comment]
> i have some comparisons here: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

Thanks, I will take a look and consider this. I like the "no index" part, as compared to something like Fuse.js. I'm assuming it will work fine in a web worker?

**Comment by leeoniya** [comment]
> I'm assuming it will work fine in a web worker?

yes, it should. if you need to highlight matched parts, and plan not to use an innerHTML string but actual DOM or JSX elements, then you'll have to run that part in the main thread. Fuse is super slow, so my recommendation with faster libs is to only use a webworker if perf becomes an issue, otherwise the complexity isnt worth it.

**Comment by leeoniya** [comment]
just noticed you're in Chicago, too :)

**Comment by mririgoyen** [comment]
> just noticed you're in Chicago, too :)

I am, nice to meet you.

**Comment by mririgoyen** [comment]
Completed in https://github.com/Pictogrammers/pictogrammers.com/pull/4.

**Comment by leeoniya** [comment]
i have some quality of life improvements coming in 0.9.5 that should help reduce userland code (unless you need to do something really custom). keep an eye out :)

https://github.com/leeoniya/uFuzzy/commit/d9b4a7cda8b59ca3cd86e607ded4cb8fd71aaeab
