### ISSUE TITLE
Advanced PNG Export - wrong icon dimension

### ISSUE THREAD

**Issue by FrancoTampieri** [Pictogrammers/pictogrammers.com#33]
Hi the export of the icon is wrong, look at this sample png:

![heart-box-outline-custom](https://user-images.githubusercontent.com/4396444/215315117-1120e29e-fbcc-42a5-883f-9e83c56f9a5c.png)

The icon would be 256x256 png image but the result is a 12x12 pixels icon on a 256x256 layer.

Kind Regards

**Comment by mririgoyen** [comment]
Hello, can you please provide reproduction steps and the browser/OS you are seeing the issue on?

**Comment by FrancoTampieri** [comment]
Sure!

I have macOS Ventura 13.1, I use Safari 16.2

The steps:
- select the icon form the search
- select on the download menu: "Advanced PNG exports..."
- select the icon dimension from default to 256
- change the foreground color (but the same beahviour happened even I didn't change the color)
- Press the download button...

(like the image I attached now)
<img width="1223" alt="Screenshot 2023-01-29 alle 15 48 18" src="https://user-images.githubusercontent.com/4396444/215334418-742f5e93-bd43-4fa0-979f-3867cf8664ca.png">

Of course with the previous version of the website that's works like a charm

Kind Regards

Franco

**Comment by mririgoyen** [comment]
Thanks for the details! I will investigate this in the next few days.

**Comment by bikathi** [comment]
I am also noticing that in my browser the size of the icon comes up like 2px. I am using the tutorial provided for installing the icons for VueJS, and using the `<svg-icon>` tag. See here:
![small_icon](https://user-images.githubusercontent.com/98804363/215344683-3fa3228e-ef44-4edc-8e65-753b6d72c7bc.png)

That small dot up there is the icon I am getting

**Comment by mririgoyen** [comment]
@Q-T5 Unless you're getting the icon from Advanced Export, that is unrelated to this issue. Please open an issue on the [vue-icon package](https://github.com/Pictogrammers/vue-icon).

@FrancoTampieri I can reproduce on Safari, so I'll work on a fix soon. In the meantime, you can use Chrome which is unaffected by this issue.

**Comment by bikathi** [comment]
@mririgoyen  Thanks for the speedy response. I am using Brave. Let me try finding other workarounds

**Comment by FrancoTampieri** [comment]
@mririgoyen that sound great! Yes in the meantime, as u suggest, I will use chrome 😊

**Comment by mririgoyen** [comment]
This should be resolved. The site is building/deploying which takes about 45m.

**Comment by mririgoyen** [comment]
Confirmed I'm able to export icons of correct size in Safari after deployment.
