### ISSUE TITLE
Contributing: UI Improvements

### ISSUE THREAD

**Issue by andrejsharapov** [Pictogrammers/pictogrammers.com#34]
Hello!

- [x]  1. I would like to help improve the site, but not in terms of functions, but in terms of interface and scss. I started by reducing the use of `background-images` on the site by replacing them with `css` pattern, but I can't test this as the command `npm run dev` throws an error:
```
info - Retrieving contributors from the API...
ReferenceError: fetch is not defined
```
Look at my changes: https://github.com/andrejsharapov/pictogrammers.com/commit/a43fea16e8ea713cf3c5d4e3f6bb37485c520bde

- [x]  2. I would advise you to use one of the commit message conventions [like this](https://github.com/andrejsharapov/nuxt-app/wiki/Commits).

- [x]  3. One more question. Do you have a site prototype in Figma that I can to duplicate and think about improving the site? This would be a good practice not only for me, but also for other users.

**Comment by mririgoyen** [comment]
1. You must be on Node 18. I'll make sure that gets added to the documentation.

2. We'll take this into consideration, but for the most part do not see the overhead a benefit for us. We're not likely to ever provide a changelog or version the site.

3. No, there is not. Things started as a XD file a long time ago, but everything else has been designed/developed in real-time.

---

Let me know if using Node 18 solves your issue.

**Comment by andrejsharapov** [comment]
Yep. 

```
info - Retrieving contributors from the API...
info - Writing 153 contributors to /public/data/contributors.json
(node:26224) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
INFO: Retrieving 7196 icons for Material Design Icons v7.1.96...   
```
But here I ran into another problem:
```
node:internal/process/esm_loader:97
     internalBinding('errors').triggerUncaughtException(
                               ^

[Error: ENOENT: no such file or directory, open 'D:\D:\...\pictogrammers.com\node_modules\@mdi\svg\svg\ab-testing.svg'] {
   errno: -4058,
   code: 'ENOENT',
   syscall: 'open',
   path: 'D:\\D:\\Development\\React\\pictogrammers.com\\node_modules\\@mdi\\svg\\svg\\ab-testing.svg'
}

Node.js v18.13.0
```

Somewhere knocking on the root.

```
path: 'D:\\D:\\
```

**Comment by mririgoyen** [comment]
You're on Windows, so there's some cross platform issues happening here I will need to investigate.

**Comment by mririgoyen** [comment]
You should be all set after pulling `main`. Fixed in https://github.com/Pictogrammers/pictogrammers.com/commit/85a3d222a3f45b62130528ef662f7d463e614d38.
