### ISSUE TITLE
Advanced export - empty png [Firefox]

### ISSUE THREAD

**Issue by przemowcf** [Pictogrammers/pictogrammers.com#36]
Hello,

Using advanced export generate only empty PNG image.
![obraz](https://user-images.githubusercontent.com/87315820/215444386-54eda1da-2ba9-4527-b85e-ebc4231fda66.png)
(87bytes 🤔 )

**Comment by mririgoyen** [comment]
In your screenshot, you're generating a 16x16 icon. 87 bytes is not empty, that's the size of an icon that small.

**Comment by przemowcf** [comment]
> In your screenshot, you're generating a 16x16 icon. 87 bytes is not empty, that's the size of an icon that small.

Hello, I checked on Chrome and it work, but not on Firefox (102.7.0esr 64bit). On Firefox I get empty images:

ab-testing-custom(16px).png:
![ab-testing-custom(16px)](https://user-images.githubusercontent.com/87315820/215740999-961d6e8a-b98d-4a50-9f8b-56c4e5b54021.png)

ab-testing-custom(24px).png:
![ab-testing-custom(24px)](https://user-images.githubusercontent.com/87315820/215741004-d2340c54-cec1-4816-93ce-8c59f2dd4451.png)

ab-testing-custom(20px).png:
![ab-testing-custom(20px)](https://user-images.githubusercontent.com/87315820/215741008-cda47233-b98f-40fc-ad50-c1de9ef0959b.png)

Here is file size comparison Chrome vs Firefox (that same: icon, size, color):
![obraz](https://user-images.githubusercontent.com/87315820/215747032-961bfae0-aa01-45ba-a841-58e40fb74feb.png)


*I have updated title as this problem exists on Firefox only*

**Comment by mririgoyen** [comment]
I've confirmed the empty PNG issue affecting Firefox only. I'll try and take a look this evening.

**Comment by mririgoyen** [comment]
This is fixed and deploying now.
