### ISSUE TITLE
Compact Icon View

### ISSUE THREAD

**Issue by HenningOI** [Pictogrammers/pictogrammers.com#46]
### Describe your suggested feature

In the old page, there was a more compact view without labels so it was more easy to find an icon.
This is no longer possible.
I never look at labels when I search for an icon, I look at the icons...

**Comment by mririgoyen** [comment]
Thanks for the suggestion. We redesigned the library view to strike a chord between usability and performance and we are happy with the balance we currently have. We invite you to use the Categories in the left column to filter your views or to utilize the Search at the top of the page.

**Comment by HenningOI** [comment]
But just hiding the labels and having the icons more compact would not affect performance?
Well I'm glad you/your team improved the performance, but the more important thing - finding icons without knowing the name - is now gone :(
Thanks anyway for all improvements.

**Comment by mririgoyen** [comment]
Reopening because last night I spent some time determining if I could get a super compact view working within performance metrics I was happy with. And I did.

**Comment by HenningOI** [comment]
Wow that was fast, thanks alot.
In my opinion this view makes most sense because nobody reads all the captions!
