### ISSUE TITLE
Scroll to learn more

### ISSUE THREAD

**Issue by mkyy** [Pictogrammers/pictogrammers.com#59]
### Before You Begin

- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The "Scroll to learn more" action button got hidden because of the screen size of my notebook.
Probably a responsive bug.

### Describe the behavior you expected

I expected to see the button clear and not hidden behind others elements.

### Steps to reproduce the issue

1. Open the website with an screen of 1525px. ( my notebook width size)
2.
3.
...

### Which browser are you experiencing the issue?

Firefox

### Which operating system are you using to run this browser?

Fedora 36

### Additional information

Hope to be helping the website to get better.

**Comment by mririgoyen** [comment]
This will be fixed on next deploy. Fixed in https://github.com/Pictogrammers/pictogrammers.com/commit/4c3230f81b10d2477b8a479e3d346ecb25bf71c4.
