### ISSUE TITLE
Play button with rounded corners

### ISSUE THREAD

**Issue by sampath-bandara** [Pictogrammers/pictogrammers.com#60]
### Describe your suggested feature

Hi,
If you can, please add the play button with rounded(smooth) corners. Thank you.

**Comment by mririgoyen** [comment]
You'll need to make that request on the appropriate library's repo. This repo is only for dealing with website issues.

MDI: https://github.com/Templarian/MaterialDesign/issues
MDIL: https://github.com/Templarian/MaterialDesignLight/issues
Memory: https://github.com/Pictogrammers/Memory/issues
