### ISSUE TITLE
advanced PNG bulk donwload

### ISSUE THREAD

**Issue by shummo** [Pictogrammers/pictogrammers.com#64]
### Describe your suggested feature

Is it possible to donwload MORE icons in specific format?

For exapample i would like to download icons in name: "light", color: white, size 256x256.

**Comment by mririgoyen** [comment]
This is not something we plan to offer at this time. The Advanced Export option fills a niche use case and we recommend that everyone uses the vector-based formats whenever possible. Using the vector formats provides the highest fidelity at any resolution and the ability to recolor any way you want, even dynamically.
