### ISSUE TITLE
Carbon Ads 

### ISSUE THREAD

**Issue by Templarian** [Pictogrammers/pictogrammers.com#72]
### Before You Begin

- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

> We have one recommendation to help improving the performance of the ads for us to continue serving ads on https://pictogrammers.com/
> I like the idea of refreshing the ad whenever the users clicks on an icon and displays the modal view. However, the users won't see the ad if they scroll down to the page. Can we not refreshing the ad on the top, but instead reloading a new ad unit inside the icon modal view?
> Something like this — you can call the [reload function](https://codepen.io/team/buysellads/pen/qMjpXO/18f70784e694e2fe28fba9ce48e65cfd) to insert the ad in a different place.

### Describe the behavior you expected

See Email

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/338885/226964490-b433b428-c197-40ba-85d0-edbc7886cd91.png)

**Comment by mririgoyen** [comment]
We're removing the auto refresh of the ad when an icon is selected on the library view. At this time, we are not interested in adding ads to the modal due to size constraints. Ads will continue to show on the full detailed icon pages as they currently do.
