### ISSUE TITLE
New emoji

### ISSUE THREAD

**Issue by simsimient1** [Pictogrammers/pictogrammers.com#75]
### Describe your suggested feature

`
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:height="24dp" android:width="24dp" 
android:viewportWidth="24" android:viewportHeight="24">
<path android:fillColor="#000000" android:pathData="M12,17.5C14.33,17.5 16.3,16.04 17.11,14H6.89C7.69,16.04 9.67,17.5 12,17.5M8.5,11A1.5,1.5 0 0,0 10,9.5A1.5,1.5 0 0,0 8.5,8A1.5,1.5 0 0,0 7,9.5A1.5,1.5 0 0,0 8.5,11M15.5,11A1.5,1.5 0 0,0 17,9.5A1.5,1.5 0 0,0 15.5,8A1.5,1.5 0 0,0 14,9.5A1.5,1.5 0 0,0 15.5,11M12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20M12,2C6.47,2 2,6.5 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"/>
</vector>`

**Comment by mririgoyen** [comment]
If you're trying to request a new icon to a library, please open an issue on the appropriate library repo. This issue tracker is only for capturing problems or feature requests for the website.
