### ISSUE TITLE
Support for animated icons

### ISSUE THREAD

**Issue by Aasikki** [Pictogrammers/pictogrammers.com#76]
### Describe your suggested feature

Sorry if this is the wrong place for this, I tried to look for the most appropriate place and couldn't find a more suited one for this.

Would it be possible to add support for animated icons? Maybe in a way that icons can have two versions, animated and non-animated. This could be very useful for example in home assistant, to have an icon animate when a device is on or doing something. Like have a little drip animation when the coffee maker is on, or a fan spinning when it's turned on. These could also be used as little one-off animations when a button is pressed, like spin the fan blades a bit when a fan os turned on, then return to the non animated state, kinda like many icons in android and Windows 11 do. This would add some really nice attention to detail for ui's using these icons, I think.

I'm not really a programmer myself, but if this kind of feature can be added, I would definitely be contributing some animated versions of the icons myself!

**Comment by mririgoyen** [comment]
This is not something we're considering at this time. Thanks for the suggestion.
