### ISSUE TITLE
Official Web Component Support

### ISSUE THREAD

**Issue by jameslovallo** [Pictogrammers/pictogrammers.com#78]
## Describe your suggested feature

It would be great to have an official MDI Web Component implementation that fetches an icon by name and allows it to be styled. Custom elements are framework agnostic, all one would need to do to use the icons is import the element and set the name property. I'd be happy to polish this up and open a PR if there's any interest.

[CodePen Example](https://codepen.io/jameslovallo/pen/XWxYzgp)

### Features

- Almost too easy to use with any site/app/platform/framework
- Low overhead
  - Script is small
  - Quickly fetches only the requested icons
  - Serves SVG from unpkg

### Example Implementation

```html
<script src=//unpkg.com/@mdi/element type="module"></script>

<mdi-icon icon="account" style="color: blue; width: 2rem;"></mdi-icon>

<mdi-icon icon="dog" style="color: brown; width: 2rem;"></mdi-icon>

<mdi-icon icon="cat" style="color: magenta; width: 2rem;"></mdi-icon>

<mdi-icon icon="car" style="color: red; width: 2rem;"></mdi-icon>

<mdi-icon icon="layers" style="color: green; width: 2rem;"></mdi-icon>
```

**Comment by mririgoyen** [comment]
Our Web Component solution is documented here: https://pictogrammers.com/docs/library/mdi/getting-started/webcomponent/

It's published under the namespace of one of our core contributors, but we have plans to move it under the @pictogrammers namespace in the future.
