### ISSUE TITLE
Search with Cyrillic letters brokes site.

### ISSUE THREAD

**Issue by arximus88** [Pictogrammers/pictogrammers.com#87]
### Before You Begin

- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When try to search with Cyrillic website brokes and show black screen with error message. To fix need to reload page.
Additional Information: Users outside English speaking countries often use few input languages on their devices, and accidentally forgetting to switch it before typing in.

### Describe the behavior you expected

a) Show default error - Not Found
b) Make search with transliteration. 

### Steps to reproduce the issue

1. Open pictogrammers.com
2. Click on Search
3. Type any Cyrillic letters. As example `є і т й ч`

### Which browser are you experiencing the issue?

Firefox 117.0b7 (64-bit), Edge 117.0b7 (64-bit)

### Which operating system are you using to run this browser?

Windows 11 (22H2)

**Comment by AndreyYolkin** [comment]
Seems like all non'latin symbols breaks the search
